Add --questions option to set number of questions
januschung/math-worksheet-generator pull request #10
Opened 2020-10-13 12:58 UTC by PrayagS

I've kept the grid size the same as before i.e. 4x2.

2020-10-13 17:01 UTC, januschung commented on run.py
> +    font_1 = "Times"
I prefer single quote for thing that doesn't need to be escaped - https://stackoverflow.com/questions/56011/single-quotes-vs-double-quotes-in-python

2020-10-13 17:04 UTC, januschung commented on run.py
> +        self.pdf.cell(
I prefer them in a single line which is easier to read.

2020-10-13 17:04 UTC, januschung commented on run.py
> +        self.pdf.cell(
similar as above...one liner is easy to read in this case

2020-10-13 17:04 UTC, januschung commented on run.py
> +            self.pdf.cell(
similar as above...one liner is easy to read in this case

2020-10-13 17:04 UTC, januschung commented on run.py
> +            self.pdf.cell(
similar as above...one liner is easy to read in this case

2020-10-13 17:07 UTC, januschung commented on run.py
> +        "--questions",
questions is a bit vague... may I suggest an other flag label like question_count? We can add a shorter flag to it such as '-q'. What do you think?

2020-10-13 17:08 UTC, januschung requested changes
Please see the comments. Other than that it is good. Thanks for taking your time mate.

2020-10-14 05:45 UTC, PrayagS commented on run.py
> +    font_1 = "Times"
Gotcha. This happened because I use black as the formatter which enforces double quotes.

2020-10-14 05:53 UTC, PrayagS commented on run.py
> +        self.pdf.cell(
This again was caused to black. I've reverted those changes.

2020-10-14 05:53 UTC, PrayagS commented on run.py
> +        self.pdf.cell(
This again was caused to black. I've reverted those changes.

2020-10-14 05:53 UTC, PrayagS commented on run.py
> +            self.pdf.cell(
This again was caused to black. I've reverted those changes.

2020-10-14 05:54 UTC, PrayagS commented on run.py
> +            self.pdf.cell(
This again was caused to black. I've reverted those changes.

2020-10-14 06:00 UTC, januschung commented
Hey @PrayagS can you resolve the conflicts when you have a chance please?

2020-10-14 06:03 UTC, PrayagS commented on run.py
> +        "--questions",
I agree. I've implemented the requested changes

2020-10-14 06:04 UTC, PrayagS commented
@januschung Sure thing. I'll let you know once I'm done resolving the conflicts.

2020-10-14 10:03 UTC, PrayagS commented
@januschung I've resolved the conflicts. Please have a look. Also if you end up accepting this PR, kindly add the `hacktoberfest-accepted` label so that it counts towards Hacktoberfest 2020.

2020-10-15 05:00 UTC, januschung commented on run.py
> +                self.print_question_row(data, (page) * page_area + self.num_x_cell, num_problems_arr[page] - self.num_x_cell,)
You give me a hard time. Accepting your code will break the existing logic to accept a different num_y_cell (say 3). 
I really like the effort you added for the question_count feature. 

If you haven't found a way to keep the existing logic, I will spend more time in the weekends to take another look.

2020-10-15 05:02 UTC, januschung commented on run.py
> +        default='80',
I think we should do something for `self.total_question = 80  # Must be a multiple of 40` since it will be confusing. Can you do something with that please?

2020-10-15 05:03 UTC, januschung commented on run.py
> +                self.print_question_row(data, (page) * page_area + self.num_x_cell, num_problems_arr[page] - self.num_x_cell,)
Can you take out the extra comma by the end on line 94 please?

2020-10-15 05:05 UTC, januschung commented on run.py
> +                self.print_question_row(data, (page) * page_area, num_problems_arr[page])
seems like we don't need the parentheses for page. Same as line 92 and 94.

2020-10-15 05:06 UTC, januschung commented on run.py
> +        quotient = int(self.total_question / (self.num_x_cell * self.num_y_cell))
maybe make use of page_area instead of recalculating self.num_x_cell * self.num_y_cell? Same for line 80 and 81.

2020-10-15 05:07 UTC, januschung commented on run.py
> +        num_problems_arr = [self.num_x_cell * self.num_y_cell] * (quotient)
We don't need the parentheses for quotient

2020-10-15 05:17 UTC, PrayagS commented on run.py
> +                self.print_question_row(data, (page) * page_area + self.num_x_cell, num_problems_arr[page] - self.num_x_cell,)
I did see PR #16 but when you change `num_y_cell`, the padding values also need to change right? Simply changing `num_y_cell` from 2 to say 3 and then printing according to that (which #16 does) produces rubbish output unless the padding values are also changed accordingly. That is why I ignored that change. Please let me know your thoughts on this.

2020-10-15 05:24 UTC, PrayagS commented on run.py
> +        default='80',
Isn't that already mentioned in the initialization part of `MathWorksheetGenerator`? Around line no. 30

2020-10-15 05:55 UTC, januschung commented on run.py
> +        default='80',
I think we can merge total_question and question_count and modify def __init__(self, type_: str, max_number: int): as def __init__(self, type_: str, max_number: int, question_count:int):

2020-10-15 05:57 UTC, januschung commented on run.py
> +                self.print_question_row(data, (page) * page_area + self.num_x_cell, num_problems_arr[page] - self.num_x_cell,)
Yes but just in case people want to play around with orientation and change the padding values (like a group of presets maybe?) That's the reason I am having headache now. I want to keep the best of both worlds.

2020-10-15 06:15 UTC, PrayagS commented on run.py
> +        default='80',
Gotcha

2020-10-15 06:15 UTC, PrayagS commented on run.py
> +                self.print_question_row(data, (page) * page_area + self.num_x_cell, num_problems_arr[page] - self.num_x_cell,)
I see. Sorry to give you a headache. I'll modify my code to accommodate that change.

2020-10-15 07:05 UTC, PrayagS commented on run.py
> +                self.print_question_row(data, (page) * page_area + self.num_x_cell, num_problems_arr[page] - self.num_x_cell,)
Please have a look again.

2020-10-16 04:38 UTC, januschung commented on run.py
> +    def split_arr(self, x: int, y: int):
I like that you make it a separate function

2020-10-16 04:39 UTC, januschung approved these changes
Let me know if I added the hacktoberfest-accepted label correctly please. Thanks for your patience and your contribution mate!

2020-10-16 07:39 UTC, PrayagS commented
Thanks for accepting the PR. The label looks correct to me. And yeah, it was my pleasure to contribute here. I wish I had something like this back when my parents used to teach me. If time permits, I might also work on adding variable grid configs.

2020-10-16 15:19 UTC, merged