fixed typos
januschung/math-worksheet-generator pull request #5
Opened 2020-10-13 07:36 UTC by kreativedev

Fixed typos on Subtraction and Multiplication

2020-10-13 17:09 UTC, januschung requested changes
Other than the file run2.py, lgtm

2020-10-13 17:09 UTC, januschung commented on run2.py
> +import argparse
Is this file being added by mistake?

2020-10-16 06:05 UTC, kreativedev commented on run2.py
> +import argparse
Was a total mistake, didn't even notice i accidentally committed that one

2020-10-16 06:12 UTC, kreativedev commented on run2.py
> +import argparse
removed the accidentally added file

2020-10-21 15:28 UTC, closed without merging